baseURL = "https://ublogger.netlify.app/"
defaultContentLanguage = "en"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
theme = "uBlogger"
themesDir = "../.."
title = "uBlogger"
[Permalinks]
posts = ":filename"
[author]
name = "upagge.en"
[languages.en]
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
hasCJKLanguage = false
languageCode = "en"
languageName = "English"
paginate = 12
weight = 1
[[languages.en.menu.main]]
identifier = "posts"
name = "Posts"
post = ""
pre = ""
title = ""
url = "/posts/"
weight = 1
[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
post = ""
pre = ""
title = ""
url = "/tags/"
weight = 2
[[languages.en.menu.main]]
identifier = "categories"
name = "Categories"
post = ""
pre = ""
title = ""
url = "/categories/"
weight = 3
[[languages.en.menu.main]]
identifier = "documentation"
name = "Docs"
post = ""
pre = ""
title = ""
url = "/categories/documentation/"
weight = 4
[[languages.en.menu.main]]
identifier = "about"
name = "About"
post = ""
pre = ""
title = ""
url = "/about/"
weight = 5
[[languages.en.menu.main]]
identifier = "github"
name = ""
post = ""
pre = "<i class='fab fa-github fa-fw'></i>"
title = "GitHub"
url = "https://github.com/upagge/ublogger"
weight = 6
[languages.en.params]
description = "About uBlogger Theme"
keywords = ["Theme", "Hugo"]
[languages.en.params.app]
iconColor = "#5bbad5"
noFavicon = false
svgFavicon = ""
themeColor = "#ffffff"
tileColor = "#da532c"
title = "uBlogger"
[languages.en.params.home]
rss = 10
[languages.en.params.home.posts]
enable = true
paginate = 6
[languages.en.params.home.profile]
avatarURL = "/images/avatar.png"
disclaimer = ""
enable = true
gravatarEmail = ""
social = true
subtitle = "A Clean, Elegant but Advanced Hugo Theme"
title = "uBlogger | Hugo Theme"
[languages.en.params.search]
absoluteURL = false
contentLength = 4000
enable = true
highlightTag = "em"
maxResultLength = 10
placeholder = ""
snippetLength = 30
type = "algolia"
[languages.en.params.search.algolia]
appID = "PASDMWALPK"
index = "index.en"
searchKey = "b42948e51daaa93df92381c8e2ac0f93"
[languages.en.params.social]
Angellist = ""
Bandcamp = ""
Behance = ""
Bilibili = ""
Bitbucket = ""
Codepen = ""
Deviantart = ""
Devto = ""
Discord = "xxxxxxxxx"
DockerHub = ""
Douban = ""
Dribbble = ""
Email = "xxxx@xxxx.com"
Facebook = "xxxx"
Fivehundredpx = ""
Flickr = ""
Foursquare = ""
FreeCodeCamp = ""
GitHub = "xxxx"
Gitea = ""
Gitlab = ""
Goodreads = ""
Googlescholar = ""
Hackernews = ""
Instagram = "xxxx"
Jsfiddle = ""
Keybase = ""
Kickstarter = ""
Lastfm = ""
Leanpub = ""
Linkedin = ""
Matrix = ""
Medium = ""
Mix = ""
Odnoklassniki = ""
Patreon = ""
Paypal = ""
Pinterest = ""
Quora = ""
RSS = true
Reddit = ""
Researchgate = ""
Skype = ""
Slidershare = ""
Snapchat = ""
Soundcloud = ""
Spotify = ""
Stackoverflow = ""
Steam = ""
Strava = ""
Telegram = "xxxx"
Thingiverse = ""
Tumblr = ""
Twitch = ""
Twitter = "xxxx"
Udemy = ""
VK = ""
Vine = ""
Weibo = ""
Whatsapp = ""
Wordpress = ""
XMPP = ""
Xing = ""
Youtubechannel = ""
Youtubecustom = ""
Youtubelegacy = "xxxx"
Zhihu = ""
[languages.en.params.social.Mastodon]
id = "@xxxx"
prefix = "https://mastodon.technology/"
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = true
noClasses = false
[markup.tableOfContents]
endLevel = 6
startLevel = 2
[mediaTypes."text/plain"]
suffixes = ["md"]
[outputFormats.MarkDown]
isHTML = false
isPlainText = true
mediaType = "text/plain"
[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
taxonomyTerm = ["HTML"]
[params]
dateFormat = "2006-01-02"
defaultTheme = "auto"
fingerprint = ""
gitRepo = "https://github.com/upagge/dolboblog-theme"
images = ["/logo.png"]
version = "2.0.X"
[params.analytics]
enable = true
[params.analytics.fathom]
id = ""
server = ""
[params.analytics.google]
anonymizeIP = true
gtag = false
id = ""
[params.analytics.yandex]
id = "70532758"
[params.cdn]
data = "jsdelivr.yml"
[params.comment]
enable = true
[params.comment.commento]
enable = false
[params.comment.disqus]
enable = false
shortname = ""
[params.comment.facebook]
appId = ""
enable = false
languageCode = ""
numPosts = 10
width = "100%"
[params.comment.gitalk]
clientId = ""
clientSecret = ""
enable = false
owner = ""
repo = ""
[params.comment.remark42]
enable = true
host = "https://comments.upagge.ru"
locale = "en"
site = "documentation"
[params.comment.telegram]
color = ""
colorful = true
dislikes = false
enable = false
height = ""
limit = 5
outlined = false
siteID = ""
[params.comment.utterances]
darkTheme = "github-dark"
enable = false
issueTerm = "pathname"
label = ""
lightTheme = "github-light"
repo = ""
[params.comment.valine]
appId = "QGzwQXOqs5JOhN4RGPOkR2mR-MdYXbMMI"
appKey = "WBmoGyJtbqUswvfLh6L8iEBr"
avatar = "mp"
emoji = ""
enable = false
enableQQ = false
highlight = true
lang = ""
meta = ""
pageSize = 10
placeholder = ""
recordIP = true
serverURLs = "https://"
visitor = true
[params.compatibility]
objectFit = false
polyfill = false
[params.cookieconsent]
enable = false
[params.cookieconsent.content]
dismiss = ""
link = ""
message = ""
[params.footer]
author = true
copyright = true
custom = ""
enable = true
hugo = true
icp = ""
license = "<a rel=\"license external nofollow noopener noreffer\" href=\"https://creativecommons.org/licenses/by-nc/4.0/\" target=\"_blank\">CC BY-NC 4.0</a>"
since = 2019
[params.header]
desktopMode = "fixed"
mobileMode = "auto"
[params.header.title]
logo = ""
name = "uBlogger"
post = ""
pre = "<i class='fas fa-pencil-alt fa-fw'></i>"
[params.list]
dateFormat = "01-02"
paginate = 20
rss = 10
[params.page]
fontawesome = true
fraction = true
hiddenFromHomePage = false
hiddenFromSearch = false
linkToMarkdown = true
rssFullText = false
ruby = true
twemoji = false
[params.page.code]
copy = true
maxShownLines = 10
[params.page.library.css]
[params.page.library.js]
[params.page.mapbox]
accessToken = "pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ"
darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
fullscreen = true
geolocate = true
lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
navigation = true
scale = true
[params.page.math]
blockLeftDelimiter = ""
blockRightDelimiter = ""
copyTex = true
enable = false
inlineLeftDelimiter = ""
inlineRightDelimiter = ""
mhchem = true
[params.page.seo]
images = []
[params.page.seo.publisher]
logoUrl = "/images/avatar.png"
name = "xxxx"
[params.page.share]
Baidu = false
Blogger = false
Buffer = false
Digg = false
Evernote = false
Facebook = true
Flipboard = false
HackerNews = true
Instapaper = false
Line = true
Linkedin = false
Mix = false
Myspace = false
Odnoklassniki = false
Pinterest = false
Pocket = false
Reddit = false
Renren = false
Skype = false
Stumbleupon = false
Trello = false
Tumblr = false
Twitter = true
VK = false
Weibo = true
Whatsapp = false
Xing = false
enable = true
[params.page.toc]
auto = true
enable = true
keepStatic = false
[params.section]
dateFormat = "01-02"
paginate = 20
rss = 10
[params.seo]
image = "/images/Apple-Devices-Preview.png"
thumbnailUrl = "/images/screenshot.png"
[params.verification]
baidu = ""
bing = ""
google = ""
pinterest = ""
yandex = ""
[privacy.googleAnalytics]
[privacy.twitter]
enableDNT = true
[privacy.youtube]
privacyEnhanced = true
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5
